---
- name: Force Nginx to pick up changes
  become: yes
  command: sudo nginx -s reload

- name: Implement Kestrel service config
  get_url:
    url: "https://raw.githubusercontent.com/Sebastian-Negoescu/assignment/master/ansible/files/kestrel-helloapp.service"
    dest: /etc/systemd/system/kestrel-helloapp.service
  become: yes

- name: Enable Kestrel service
  become: yes
  command: sudo systemctl enable kestrel-helloapp.service

- name: Start Kestrel service
  become: yes
  command: sudo systemctl start kestrel-helloapp.service
